---

- name: Ensure Gitea image is pulled
  community.docker.docker_image:
    name: "{{ gitea_gitea_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ gitea_gitea_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else gitea_gitea_container_image_force_pull }}"

- name: Ensure Gitea paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_uid }}"
  with_items:
    - "{{ gitea_gitea_base_path }}"
    - "{{ gitea_gitea_data_dir_path }}"
    - "{{ gitea_gitea_config_dir_path }}"

- name: Ensure Gitea support files created
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ gitea_gitea_base_path }}/{{ item }}"
    owner: "{{ gitea_uid }}"
    group: "{{ gitea_uid }}"
    mode: 0640
  with_items:
    - env
    - labels

- name: Ensure gitea-gitea.service installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/gitea-gitea.service.j2"
    dest: "/etc/systemd/system/gitea-gitea.service"
    mode: 0640
  register: gitea_gitea_systemd_service_result

- name: Ensure systemd reloaded after gitea-gitea.service installation
  ansible.builtin.service:
    daemon_reload: true
  when: gitea_gitea_systemd_service_result.changed
